version: '3'

tasks:
  get_debian:
    cmds:
      - ./bash/get_debian.sh

  build:
    cmds:
      - ansible-playbook --inventory ./ansible/hosts.yml -l void-hw ./ansible/build.yml
    silent: true
    sources:
