version: '3'

tasks:
  build:
    deps: [reset_target]
    cmds:
      - ansible-playbook --inventory ./ansible/hosts.yml -l void-hw ./ansible/build.yml
    silent: true

  default:
    deps: [build]
    silent: true

  get_debian:
    cmds:
      - ./bash/get_debian.sh
    silent: true

  reset_target:
    cmds:
      - ./bash/reset_target.sh
    silent: true

  # TODO: make default, do build as a dep.
  test:
    cmds:
      - ansible-playbook --inventory ./ansible/hosts.yml -l void-hw ./ansible/test.yml
    silent: true
