version: '3'

tasks:
  build:
    cmds:
      - ansible-playbook --inventory ./ansible/hosts.yml -l void-hw ./ansible/build.yml
    silent: true

  get_debian:
    cmds:
      - ./bash/get_debian.sh
    silent: true

  reset_target:
    cmds:
      - ./bash/reset_target.sh
    silent: true
