---
- hosts: all
  tasks:
    - name: update packages
      apt:
        name: "*"
        state: latest
      become: yes

    - name: update development tools
      apt:
        name: build-essential
        state: latest
      become: yes

    - name: get kernel version
      shell: uname -r
      register: kernel

    - name: install kernel headers
      apt:
        name: "linux-headers-{{ kernel.stdout_lines[0] }}"
        state: latest
      become: yes

    - name: build module
      ansible.builtin.shell: make
      args:
        chdir: /vagrant/src

    - name: insert  module
      shell: insmod yeet.ko
      args:
        chdir: /vagrant/src
      become: yes

    - name: copy module to lib
      copy:
        src: /vagrant/src/yeet.ko
        dest: "/lib/modules/{{ kernel.stdout_lines[0] }}"
        remote_src: yes
      become: yes

    - name: add module to list
      lineinfile:
        path: /etc/modules
        line: yeet
        create: yes
      become: yes

    - name: update module dependencies
      command: depmod
      become: yes

    - name: reboot
      reboot:
      become: yes
