---
- hosts: void-hw
  tasks:
    # initialization test
    - name: check init
      shell: dmesg | grep -q "preparing to yeet."
      become: yes
      register: check_init

    - name: notify init pass
      debug:
        msg: "PASS: module initializes!"
      when: not check_init.failed

    - name: notify init fail
      debug:
        msg: "FAIL: module failed to initialize"
      when: check_init.failed

    # task test
    - name: check task
      shell: dmesg | grep -q "(╯°□°）╯︵ ┻━┻"
      become: yes
      register: check_task

    - name: notify task pass
      debug:
        msg: "PASS: module executes task!"
      when: not check_task.failed

    - name: notify task fail
      debug:
        msg: "FAIL: module failed to execute task"
      when: check_task.failed

    # exit test
    - name: remove module
      shell: rmmod void_hw
      become: yes

    - name: check exit
      shell: dmesg | grep -q "yeeting complete."
      become: yes
      register: check_exit

    - name: notify exit pass
      debug:
        msg: "PASS: module exits!"
      when: not check_exit.failed

    - name: notify init fail
      debug:
        msg: "FAIL: module failed to initialize"
      when: check_exit.failed
